apiVersion: v1
kind: Pod
metadata:
  annotations:
    my-key: my-value
  labels:
    name: dns-frontend
  name: dns-frontend
  namespace: my-namespace
spec:
  containers:
  - command:
    - python
    - client.py
    - http://dns-backend.development.svc.cluster.local:8000
    image: registry.k8s.io/example-dns-frontend:v1
    imagePullPolicy: Always
    name: dns-frontend
  restartPolicy: Never
